services:
  serve:
    container_name: spring83
    build: &default-build-spec
      context: .
      dockerfile: Dockerfile
      target: serve
    network_mode: "host"
    env_file:
      - .local.env
    volumes: 
      - ./content:/content

